# Simple Cloud Build configuration for Interior AI Service
# Runs on push to main branch - builds, tests, and deploys

steps:
  # Step 1: Run tests and code quality checks
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🧪 Running tests and code quality checks..."
        
        # Create a test container with our code
        docker create --name test-container python:3.11-slim
        docker cp . test-container:/app
        docker start test-container
        
        # Install uv and dependencies
        docker exec test-container bash -c "
          pip install --no-cache-dir uv &&
          cd /app &&
          uv sync --frozen --no-dev &&
          uv run pip install pytest pytest-cov ruff bandit
        "
        
        # Run code quality checks
        docker exec test-container bash -c "
          cd /app &&
          echo '🔍 Running ruff linting...' &&
          uv run ruff check . &&
          echo '✨ Running ruff formatting...' &&
          uv run ruff format --check . &&
          echo '🔒 Running security scanning...' &&
          uv run bandit -r app/ || true
        "
        
        # Run unit tests
        docker exec test-container bash -c "
          cd /app &&
          echo '🧪 Running unit tests...' &&
          uv run pytest tests/unit/ -v
        "
        
        # Clean up test container
        docker stop test-container
        docker rm test-container
        
        echo "✅ Tests completed"

  # Step 2: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_GCP_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REGISTRY}/${_SERVICE_NAME}:$COMMIT_SHA'
      - '-t'
      - '${_GCP_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REGISTRY}/${_SERVICE_NAME}:latest'
      - '-f'
      - 'Dockerfile'
      - '.'
    id: 'build-image'

  # Step 3: Push Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "📦 Pushing Docker images to Artifact Registry..."
        echo "Repository: ${_GCP_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REGISTRY}/${_SERVICE_NAME}"
        echo "Tags: $COMMIT_SHA, latest"
        
        # List images to verify they exist
        docker images | grep interior-ai-service
        
        # Push images
        docker push "${_GCP_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REGISTRY}/${_SERVICE_NAME}:$COMMIT_SHA"
        docker push "${_GCP_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REGISTRY}/${_SERVICE_NAME}:latest"
        
        echo "✅ Images pushed successfully"
    id: 'push-image'
    waitFor: ['build-image']

  # Step 4: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - '${_GCP_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REGISTRY}/${_SERVICE_NAME}:$COMMIT_SHA'
      - '--region'
      - '${_GCP_REGION}'
      - '--platform'
      - 'managed'
      - '--service-account'
      - 'interior-ai-service@$PROJECT_ID.iam.gserviceaccount.com'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--max-instances'
      - '20'
      - '--min-instances'
      - '1'
      - '--set-env-vars'
      - 'ENVIRONMENT=production,GOOGLE_CLOUD_PROJECT=$PROJECT_ID,VERTEX_AI_LOCATION=europe-north1,PUBSUB_TOPIC=form-submissions-topic'
      - '--set-secrets'
      - 'DESIGNER_EMAIL=designer-email:latest,SMTP_USERNAME=smtp-username:latest,SMTP_PASSWORD=smtp-password:latest'
    id: 'deploy-cloud-run'
    waitFor: ['push-image']

  # Step 5: Run health checks
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🏥 Running health checks..."
        
        # Wait for deployment to be ready
        sleep 30
        
        # Get the service URL
        RUN_SERVICE_URL=$$(gcloud run services describe ${_SERVICE_NAME} --region=${_GCP_REGION} --format='value(status.url)')
        
        # Run health checks
        echo "Checking service at: $$RUN_SERVICE_URL"
        
        # Basic health check
        curl -f "$$RUN_SERVICE_URL/health/" || exit 1
        
        # Readiness check
        curl -f "$$RUN_SERVICE_URL/health/readiness" || exit 1
        
        echo "✅ Health checks passed"
        echo "🚀 Deployment successful! Service URL: $$RUN_SERVICE_URL"
    waitFor: ['deploy-cloud-run']

# Build options
options:
  logging: CLOUD_LOGGING_ONLY

# Build timeout
timeout: '1200s'

# Substitutions
substitutions:
  _GCP_REGION: europe-north1
  _SERVICE_NAME: interior-ai-service
  _ARTIFACT_REGISTRY: interior-ai-service

# Available images
images:
  - '${_GCP_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REGISTRY}/${_SERVICE_NAME}:$COMMIT_SHA'
  - '${_GCP_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REGISTRY}/${_SERVICE_NAME}:latest'

 